### PR TITLE
Refactor server

### PR DESCRIPTION
**Pull request by alxwrd**
This takes functionallity in `server.py` and extracts it into a class. The idea is to allow an interface to a running server by calling methods on an object.

As to not introduce breaking changes, a default instance of `Server` is created in the `core.__init__.py`, which means other modules will still be able to do:

```python
from core import server

server.start()
```

However, there is now the ability to create instances of a server:

```python

from core import Server

server1 = Server(port=1234, log="server1.log")
server1.start()

server2 = Server(port=4567, log="server2.log")
server2.start()
```

I also noted that `stop` and `simulate` were doing the similar things, so I have extracted them out into the method `_run_command`. `stop` and `simulate` now pass in the relevent arguments to this method.

Hope these changes are ok, and don't come across as overbearing. 🎉

### CODE REVIEW

**Comment by glinskyc** [comment]
Alex, thanks for the contributions!  I think making the server functionality into its own class is a smart way to go.  After my initial write of the code, I considered changing to a class-based approach, so it's great to see someone doing it!  I'll take a closer look at your commits and test some things out before merging.

**Comment by alxwrd** [comment]
Thank you! Yes, please let me know if anything doesn't work quite right and I can submit some changes.

**Comment by glinskyc** [comment]
Unfortunately, I no longer have access to the commercial software required to test this or any other requests.  I just wanted to let you (and anyone else seeing this) know.

**Comment by alxwrd** [comment]
@glinskyc no worries. I'll close this PR.

**Pull request closed without merging**
